spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET}
  alert-service:
    url: http://localhost:8082
  opensky:
    base-url: ${OPENSKY_BASE_URL:https://opensky-network.org}
    username: ${OPENSKY_USERNAME}
    password: ${OPENSKY_PASSWORD}
  kac:
    service-key: ${KAC_SERVICE_KEY}

---
spring:
  config:
    activate:
      on-profile: demo

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/flight_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

app:
  alert-service:
    url: http://alert-service:8082

---
spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/flight_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

app:
  alert-service:
    url: http://alert-service.railway.internal:8082

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
